baseurl = "https://asktao.github.io"
title = "asktao"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"

#disqusShortname = "asktao"

#[params]
#  author = "asktao"
#  info = "R&D"
#  description = "asktao's personal website"
#  keywords = "blog,developer,personal"
#  #avatarurl = "images/avatar.jpg"
#  #gravatar = "john.doe@example.com"
#
#  #favicon_32 = "/img/favicon-32x32.png"
#  #favicon_16 = "/img/favicon-16x16.png"
#
#  #since = 2019
#
#  enableTwemoji = true
#
#  colorScheme = "auto"
#  hidecolorschemetoggle = false
#
#  customCSS = ["css/custom.css"]
#  customSCSS = ["scss/custom.scss"]
#  customJS = ["js/custom.js"]
#
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "asktao"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/asktao/"
##[[params.social]]
##  name = "Gitlab"
##  icon = "fa fa-gitlab fa-2x"
##  weight = 2
##  url = "https://gitlab.com/johndoe/"
##[[params.social]]
##  name = "Twitter"
##  icon = "fa fa-twitter fa-2x"
##  weight = 3
##  url = "https://twitter.com/johndoe/"
##
## Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "https://asktao.me/About-me-7326ca879d364d58abea991d59c8ff13"
